#pragma once

#include "utils/common.h"

typedef enum {
	TOK_EOF,
	TOK_UNKNOWN,

	TOK_INT,
	TOK_FLOAT,
	TOK_STRING,
	TOK_CHAR,
	TOK_IDENT,

	TOK_KEYWORD_LET,
	TOK_KEYWORD_MUT,
	TOK_KEYWORD_CONST,
	TOK_KEYWORD_IF,
	TOK_KEYWORD_THEN,
	TOK_KEYWORD_ELSE,
	TOK_KEYWORD_PUB,
	TOK_KEYWORD_FUNC,
	TOK_KEYWORD_RETURN,
	TOK_KEYWORD_BREAK,
	TOK_KEYWORD_CONTINUE,
	TOK_KEYWORD_STRUCT,
	TOK_KEYWORD_TEST,
	TOK_KEYWORD_FOR,
	TOK_KEYWORD_WHILE,

	TOK_PLUS,
	TOK_MINUS,
	TOK_ASTERISK,
	TOK_SLASH,
	TOK_PERCENT, // !
	TOK_BACKSLASH,
	TOK_MINUS_RARROW,
	TOK_EQ_RARROW, // !
	TOK_EQ,
	TOK_EQ_EQ,
	TOK_LARROW,
	TOK_RARROW,
	TOK_LARROW_EQ,
	TOK_RARROW_EQ,
	TOK_AMP, // !
	TOK_AMP_AMP, // !
	TOK_PIPE, // !
	TOK_PIPE_PIPE, // !
	TOK_COLON,
	TOK_COLON_COLON,
	TOK_SEMICOLON,
	TOK_COMMA,
	TOK_DOT,
	TOK_DOT_DOT,
	TOK_BANG, // !
	TOK_BANG_EQ, // !
	TOK_AT,

	TOK_LPAREN,
	TOK_RPAREN,
	TOK_LBRACK,
	TOK_RBRACK,
	TOK_LBRACE,
	TOK_RBRACE,
} TokenType;

const char* describeTokenType(TokenType type);

typedef struct {
	TokenType type;
	const char* start;
	size_t length;
	uint32_t line;
	uint32_t col;
} Token;