const std = @import("std");

const c = @cImport({
    @cInclude("compiler/compiler.h");
    @cInclude("vm/debug.h");
});

const clap = @import("clap");

const Subcommands = enum {
    build,
    cst,
};

const main_parsers = .{
    .command = clap.parsers.enumeration(Subcommands),
};

const main_params = clap.parseParamsComptime(
    \\-h, --help  Display this help
    \\<command>  Either 'build' or 'cst'
    \\
);

const MainArgs = clap.ResultEx(clap.Help, &main_params, main_parsers);

pub fn main() !void {
    const gpa = std.heap.page_allocator;

    var buffer: [1024]u8 = undefined;
    var stdout_bw = std.fs.File.stdout().writer(&buffer);
    var stdout = &stdout_bw.interface;

    defer stdout.flush() catch {};

    var iter = try std.process.ArgIterator.initWithAllocator(gpa);
    defer iter.deinit();

    _ = iter.next();

    var res = try clap.parseEx(
        clap.Help,
        &main_params,
        main_parsers,
        &iter,
        .{
            .allocator = gpa,
            .terminating_positional = 0,
        },
    );
    defer res.deinit();

    if (res.args.help != 0)
        return clap.help(stdout, clap.Help, &main_params, .{});

    const command = res.positionals[0] orelse {
        try stdout.print("[Error] Expected a command\n", .{});
        return;
    };
    try buildMain(command, gpa, stdout, &iter);
}

fn buildMain(
    command: Subcommands,
    gpa: std.mem.Allocator,
    writer: *std.Io.Writer,
    iter: *std.process.ArgIterator,
) !void {
    const params = comptime clap.parseParamsComptime(
        \\-h, --help  Display this help and exit.
        \\<str>
        \\
    );

    var res = try clap.parseEx(
        clap.Help,
        &params,
        clap.parsers.default,
        iter,
        .{
            .allocator = gpa,
        },
    );
    defer res.deinit();

    if (res.args.help != 0)
        return clap.help(writer, clap.Help, &params, .{});

    const filename = res.positionals[0] orelse {
        try writer.print("[Error] Expected an argument\n", .{});
        return;
    };

    const file = std.fs.cwd().openFile(
        filename,
        .{ .mode = .read_only },
    ) catch {
        try writer.print("[Error] Could not open file {s}\n", .{filename});
        return;
    };

    const stat = try file.stat();

    const file_contents = try gpa.alloc(u8, stat.size + 1);
    _ = try file.readAll(file_contents);
    file_contents[stat.size] = 0; // sentinel terminate for C interoperation

    if (command == .cst) {
        c.compileCst(file_contents.ptr, filename.ptr);
    }

    var bytecode: c.struct_Chunk = undefined;
    const result = c.compile(file_contents.ptr, filename.ptr, &bytecode);
    if (result > 0) return;

    c.disassembleChunk(&bytecode, "Generated Bytecode");

    c.freeChunk(&bytecode);
}
