#include "vm/chunk.h"
#include "vm/debug.h"
#include "vm/vm.h"
#include "compiler/compiler.h"

#include <stdio.h>

int main () {
	Chunk bytecode = compile("let hello = 0");

	disassembleChunk(&bytecode, "Generated Bytecode");
	
	initVM();

	evaluate(&bytecode);

	freeVM();
	freeChunk(&bytecode);

	return 0;
}