const std = @import("std");

const c = @cImport({
    @cInclude("compiler/compiler.h");
    @cInclude("vm/debug.h");
});

const clap = @import("clap");

const Subcommands = enum {
    build,
    cst,
};

const main_parsers = .{
    .command = clap.parsers.enumeration(Subcommands),
};

const main_params = clap.parseParamsComptime(
    \\-h, --help  Display this help
    \\<command>  Either 'build' or 'cst'
    \\
);

const MainArgs = clap.ResultEx(clap.Help, &main_params, main_parsers);

fn cliError(writer: *std.Io.Writer, comptime fmt: []const u8, args: anytype) std.Io.Writer.Error!void {
    try writer.writeAll("\x1b[1;31m[Error] \x1b[0m");
    try writer.print(fmt, args);
    try writer.writeByte('\n');
}

pub fn main() !u8 {
    const gpa = std.heap.page_allocator;

    var buffer: [1024]u8 = undefined;
    var stdout_bw = std.fs.File.stdout().writer(&buffer);
    var stdout = &stdout_bw.interface;

    defer stdout.flush() catch {};

    var iter = try std.process.ArgIterator.initWithAllocator(gpa);
    defer iter.deinit();

    _ = iter.next();

    var res = clap.parseEx(
        clap.Help,
        &main_params,
        main_parsers,
        &iter,
        .{
            .allocator = gpa,
            .terminating_positional = 0,
        },
    ) catch |err| {
        if (err == error.NameNotPartOfEnum) {
            try cliError(stdout, "Unknown command", .{});
            return 1;
        }
        return err;
    };
    defer res.deinit();

    if (res.args.help != 0) {
        try clap.help(stdout, clap.Help, &main_params, .{});
        return 0;
    }

    const command = res.positionals[0] orelse {
        try cliError(stdout, "Expected a command", .{});
        return 1;
    };
    return buildMain(command, gpa, stdout, &iter);
}

fn buildMain(
    command: Subcommands,
    gpa: std.mem.Allocator,
    writer: *std.Io.Writer,
    iter: *std.process.ArgIterator,
) !u8 {
    const params = comptime clap.parseParamsComptime(
        \\-h, --help  Display this help and exit.
        \\<str>
        \\
    );

    var res = try clap.parseEx(
        clap.Help,
        &params,
        clap.parsers.default,
        iter,
        .{
            .allocator = gpa,
        },
    );
    defer res.deinit();

    if (res.args.help != 0) {
        try clap.help(writer, clap.Help, &main_params, .{});
        return 0;
    }

    const filename = res.positionals[0] orelse {
        try cliError(writer, "Expected an argument", .{});
        return 1;
    };

    const file = std.fs.cwd().openFile(
        filename,
        .{ .mode = .read_only },
    ) catch {
        try cliError(writer, "Could not open file {s}", .{filename});
        return 1;
    };

    const stat = try file.stat();

    const file_contents = try gpa.alloc(u8, stat.size + 1);
    _ = try file.readAll(file_contents);
    file_contents[stat.size] = 0; // sentinel terminate for C interoperation

    if (command == .cst) {
        c.compileCst(file_contents.ptr, filename.ptr);
    }

    var bytecode: c.struct_Chunk = undefined;
    const result = c.compile(file_contents.ptr, filename.ptr, &bytecode);
    if (result > 0) return 1;

    c.disassembleChunk(&bytecode, "Generated Bytecode");

    c.freeChunk(&bytecode);

    return 0;
}
