#include "vm/chunk.h"
#include "vm/debug.h"
#include "vm/vm.h"
#include "compiler/compiler.h"

#include <iostream>
#include <string>
#include <vector>

#include "cli/cli_parser.hpp"

using std::string;

int main (int argc, const char** argv) {

	auto parser = ArgsParser(argc, argv)
		.setDescription("Wyrm programming language")
		.setHelpMessage("Use 'wyrm help' for help on the CLI")
		.addSubcommand(Subcommand("help", "display CLI help", 0))
		.addSubcommand(Subcommand("build", "compile Wyrm source", 1));

	ArgsInfo info = parser.parse();

	if (info.subcommand == "help") {
		parser.printHelp();
		exit(0);
	}

	if (info.subcommand != "build") {
		exit(1);
	}

	FILE* fp = fopen(info.args[0], "r");
	if (fp == NULL) {
		cliError("Could not open file %s", info.args[0]);
		exit(1);
	}

	fseek(fp, 0, SEEK_END);
	size_t fileSize = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	char* fileContents = (char*)malloc(sizeof(char) * (fileSize + 1));
	size_t charsRead = fread(fileContents, sizeof(char), fileSize, fp);
	fileContents[fileSize] = '\0';

	Chunk bytecode = compile(fileContents, info.args[0]);

	disassembleChunk(&bytecode, "Generated Bytecode");
	
	//initVM();

	//evaluate(&bytecode);

	freeVM();
	freeChunk(&bytecode);

	return 0;
}