#include "vm/chunk.h"
#include "vm/debug.h"
#include "vm/vm.h"
#include "compiler/lexer/lexer.h"
#include "compiler/parser/parser.h"
#include "compiler/ast.h"
#include "utils/memory.h"
#include "compiler/error/error.h"
#include "compiler/codegen/codegen.h"

#include <stdio.h>

int main () {
	ArenaAllocator allocator;
	arenaInit(&allocator, 1024);
	
	initLexer(&allocator, "1 + 2 - 65");
	ASTNode* program = parse(&allocator);
	if (errorsCount() > 0) {
		printErrors();
		return 1;
	}
	printAST(program, 0);
	Chunk bytecode = generateBytecode(program);
	if (errorsCount() > 0) {
		printErrors();
		return 1;
	}

	printf("Arena allocated %lu bytes\n", allocator.totalAllocated);
	arenaDestroy(&allocator);

	disassembleChunk(&bytecode, "Generated Bytecode");
	
	initVM();

	evaluate(&bytecode);

	freeVM();
	freeChunk(&bytecode);

	return 0;
}