const std = @import("std");

const c = @cImport({
    @cInclude("compiler/compiler.h");
    @cInclude("vm/debug.h");
});

pub fn main() !void {
    const gpa = std.heap.page_allocator;
    const args = try std.process.argsAlloc(gpa);
    defer std.process.argsFree(gpa, args);

    var buffer: [256]u8 = undefined;
    const stdout_bw = std.fs.File.stdout().writer(&buffer);
    var stdout = stdout_bw.interface;

    defer stdout.flush() catch {};

    if (args.len <= 1) {
        try stdout.print("[Error] Expected a command\n", .{});
        return;
    }

    if (std.mem.eql(u8, args[1], "help")) {
        try stdout.print("Use 'wyrm help' for help on the CLI\n", .{});
        return;
    }

    if (!std.mem.eql(u8, args[1], "build")) {
        try stdout.print("[Error] Unknown command {s}\n", .{args[1]});
        return;
    }

    if (args.len != 3) {
        try stdout.print("[Error] Expected {d} arguments, got {d}\n", .{ 1, args.len - 2 });
        return;
    }

    const file = std.fs.cwd().openFile(
        args[2],
        .{ .mode = .read_only },
    ) catch {
        try stdout.print("[Error] Could not open file {s}\n", .{args[2]});
        return;
    };
    const stat = try file.stat();

    const file_contents = try gpa.alloc(u8, stat.size + 1);
    _ = try file.readAll(file_contents);
    file_contents[stat.size] = 0; // sentinel terminate for C interoperation

    var bytecode: c.struct_Chunk = undefined;
    const result = c.compile(file_contents.ptr, args[2].ptr, &bytecode);
    if (result > 0) return;

    c.disassembleChunk(&bytecode, "Generated Bytecode");

    c.freeChunk(&bytecode);
}
