#include "vm/chunk.h"
#include "vm/debug.h"
#include "vm/vm.h"
#include "compiler/compiler.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cli_utils/cli_utils.h"

int main (int argc, const char** argv) {

	ArgsParser parser;
	argsParserInit(&parser, "Wyrm programming language", "Use 'wyrm help' for help on the CLI", argc, argv);
	addSubcommand(&parser, "build", "compile wyrm source", 1, 0);
	addSubcommand(&parser, "help", "display cli help", 0, 0);
	ArgsInfo info = parseArgs(&parser);

	if (strcmp(info.subcommand, "help") == 0) {
		printHelp(&parser);
		exit(0);
	}

	FILE* fp = fopen(vectorGet(&info.args, 0), "r");
	if (fp == NULL) {
		cliError("Could not open file %s", vectorGet(&info.args, 0));
		exit(1);
	}

	fseek(fp, 0, SEEK_END);
	size_t fileSize = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	char* fileContents = (char*)malloc(sizeof(char) * (fileSize + 1));
	size_t charsRead = fread(fileContents, sizeof(char), fileSize, fp);
	fileContents[fileSize] = '\0';

	Chunk bytecode = compile(fileContents, vectorGet(&info.args, 0));

	disassembleChunk(&bytecode, "Generated Bytecode");
	
	//initVM();

	//evaluate(&bytecode);

	freeVM();
	freeChunk(&bytecode);

	argsParserFree(&parser);
	vectorFree(&info.flags);
	vectorFree(&info.args);

	return 0;
}